sudo: true
language: node_js
node_js:
  - "8"

cache:
  directories:
    - $HOME/.npm
    - /usr/local/lib/node_modules

before_script:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build
  - node script/modify.js 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: _book
  target_branch: gh-pages
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: never
